sudo: required

branches:
  only:
    - master
    - index-page
    - /201[7-9][0-1][0-9][0-3][0-9]/

cache: yarn

language: node_js

before_install:
  - export TZ=Europe/Helsinki

install: true

services:
  - docker

jobs:
  include:
    - stage: test
      env: LINT,UNIT,FLOW
      node_js: '10'
      script:
        - yarn install
        - yarn lint
        - yarn test-coverage
        - yarn test-report
        - test/flow.sh
    - stage: test
      env: _SMOKE=1
      node_js: '10'
      script: test/smoke.sh

    - stage: visual
      env: VISUAL=chrome
      node_js: '10'
      script: test/visual.sh
    - stage: visual
      env: VISUAL=ie11
      node_js: '10'
      script: test/visual.sh
    - stage: visual
      env: VISUAL=edge17
      node_js: '10'
      script: test/visual.sh
    - stage: visual
      env: VISUAL=safari11
      node_js: '10'
      script: test/visual.sh
    - stage: visual
      env: VISUAL=firefox
      node_js: '10'
      script: test/visual.sh

    - stage: build and deploy container
      node_js: '10'
      script: test/deploy.sh
